#!/usr/bin/env bash
# Reset .env to point at the project's default (main / production)
# Lakebase branch, regardless of the current git branch.
#
# Substrate-only: delegates to `lakebase-branch sync-env --branch main`
# (TS) which honors the trunk-alias mapping (git "main"/"master" resolves
# to the Lakebase default leaf, e.g. "production"). Spring tail mirrors
# refresh-token.sh so Java users can `./mvnw spring-boot:run` after
# resetting to main.
#
# Usage: ./scripts/connect-main-branch.sh
set -euo pipefail

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "connect-main-branch: must run from a git repo." >&2
  exit 1
fi
cd "$WORK_TREE"

BIN="$WORK_TREE/node_modules/.bin/lakebase-branch"
if [ ! -x "$BIN" ]; then
  ALT="$WORK_TREE/node_modules/@databricks-solutions/lakebase-scm-utils/dist/scripts/lakebase/branch.cli.js"
  if [ ! -f "$ALT" ]; then
    echo "connect-main-branch: lakebase-scm-utils not installed. Run 'npm install'." >&2
    exit 1
  fi
  node "$ALT" sync-env --cwd "$WORK_TREE" --branch main
else
  "$BIN" sync-env --cwd "$WORK_TREE" --branch main
fi

if [ -f pom.xml ]; then
  set -a
  # shellcheck source=/dev/null
  source .env 2>/dev/null || true
  set +a
  {
    echo "# Auto-generated by connect-main-branch.sh for branch: ${LAKEBASE_BRANCH_ID:-unknown}"
    echo "# No password: the app mints a short-lived Lakebase token at runtime."
    echo "spring.datasource.url=jdbc:postgresql://${LAKEBASE_HOST:-}:5432/${PGDATABASE:-databricks_postgres}?sslmode=require&ApplicationName=${PGAPPNAME:-scm-utils/0.2.36}"
    echo "spring.datasource.username=${DB_USERNAME:-}"
  } > application-local.properties
fi

echo "Connected to default Lakebase branch ('${LAKEBASE_BRANCH_ID:-?}'). Updated .env and application-local.properties."
