#!/usr/bin/env bash
# Refresh Lakebase short-lived credentials for the current git branch.
#
# Substrate-only: delegates to `lakebase-branch sync-env` (TS) for the
# .env rewrite + credential mint + git-branch -> Lakebase-leaf mapping.
# Keeps a small Spring tail that writes application-local.properties
# when pom.xml is detected, so Java users do not have to source .env
# into their Maven invocation manually.
#
# Usage:
#   ./scripts/refresh-token.sh                    # refresh only
#   ./scripts/refresh-token.sh ./mvnw spring-boot:run
set -euo pipefail

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "refresh-token: must run from a git repo." >&2
  exit 1
fi
cd "$WORK_TREE"

# Resolve the kit's lakebase-branch bin. Prefer the npm-installed
# .bin symlink; fall back to the on-disk dist file so fresh clones
# (pre-install) and CI runners both work.
BIN="$WORK_TREE/node_modules/.bin/lakebase-branch"
if [ ! -x "$BIN" ]; then
  ALT="$WORK_TREE/node_modules/@databricks-solutions/lakebase-scm-utils/dist/scripts/lakebase/branch.cli.js"
  if [ ! -f "$ALT" ]; then
    echo "refresh-token: lakebase-scm-utils not installed. Run 'npm install'." >&2
    exit 1
  fi
  node "$ALT" sync-env --cwd "$WORK_TREE"
else
  "$BIN" sync-env --cwd "$WORK_TREE"
fi

# Spring tail: mirror SPRING_DATASOURCE_* into application-local.properties
# when pom.xml is present. Values are already in .env after sync-env;
# this projection is the only piece TS sync-env does not own (kept here
# as honest templating, not substrate logic).
if [ -f pom.xml ]; then
  set -a
  # shellcheck source=/dev/null
  source .env 2>/dev/null || true
  set +a
  {
    echo "# Auto-generated by refresh-token.sh for branch: ${LAKEBASE_BRANCH_ID:-unknown}"
    echo "# No password: the app mints a short-lived Lakebase token at runtime."
    echo "spring.datasource.url=jdbc:postgresql://${LAKEBASE_HOST:-}:5432/${PGDATABASE:-databricks_postgres}?sslmode=require&ApplicationName=${PGAPPNAME:-scm-utils/0.2.36}"
    echo "spring.datasource.username=${DB_USERNAME:-}"
  } > application-local.properties
fi

echo "Lakebase: token refreshed for branch '${LAKEBASE_BRANCH_ID:-?}'."

if [ $# -gt 0 ]; then
  exec "$@"
fi
